# Site settings | 网站设置
title: sthoo
SEOTitle: sthoo的博客
header-img: img/home-bg-he.png
email: 1161694014@qq.com
description: "sthoo的博客"
keyword: "sthoo的博客, Tensorflow,Spark, Python blog"
url: "http://hsh0107.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'


# Sidebar settings | 侧边栏设置
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "就算这样,也得去尝试啊!"
sidebar-avatar: /img/head.jpg      # 头像





# SNS settings | 社交网络设置
facebook_username: xx
# github_username: hsh0107
zhihu_username: xx
csdn_username: 1161694014@qq.com




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
# permalink: pretty
paginate: 5
paginate_path: "page:num"
# 转换时排除某些文件夹或文件。被排除的文件或文件夹的路径是相对于网站源码目录的，源码目录以外不受影响。
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

Regeneration: true    # 允许文件修改时自动重新生成网站。





# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# Gitalk
gitalk:
  enable: true    # 是否开启Gitalk评论
  clientID: 51d4d88b787e2a67b38d                            #生成的clientID
  clientSecret: 4845266c032e7b8ee1f1b5a9aac553dfdf696cca    #生成的clientSecret
  repo: hsh0107.github.io    #仓库名称
  owner: hsh0107    # github用户名
  admin: hsh0107
  distractionFreeMode: true # 是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 9acee03023ad0c6c993dd86df81e2ac8


# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "杨保长的魔幻云",
        href: "http://blog.magiccloudnet.com"
    },{
        title: "杨保长的博客",
        href: "https://www.zksfyz.com/"
    }
]

theme: jekyll-theme-midnight